### ISSUE TITLE
doesn't handle dynamic `import()`s

### ISSUE THREAD

**Issue by dgoldstein0** [piuccio/rollup-plugin-amd#17]
I am working on rolluping a codebase that currently compiles to AMD.  I'm still searching for the right configuration, but a simple one that I thought might work, which doesn't, is to just use the `amd()` plugin with no options - making it apply to all my code.  This fails with a stack trace that looks like:

```
SyntaxError: 'import' and 'export' may only appear at the top level
    at Parser.instance.raise.instance.raiseRecoverable (node_modules/rollup-plugin-amd/node_modules/espree/espree.js:417:19)
    at Parser.pp$1.parseStatement (node_modules/rollup-plugin-amd/node_modules/acorn/dist/acorn.js:797:16)
    at Parser.pp$1.parseBlock (node_modules/rollup-plugin-amd/node_modules/acorn/dist/acorn.js:1112:23)
    at Parser.pp$1.parseStatement (node_modules/rollup-plugin-amd/node_modules/acorn/dist/acorn.js:791:34)
    at Parser.pp$1.parseIfStatement (node_modules/rollup-plugin-amd/node_modules/acorn/dist/acorn.js:931:26)
    at Parser.pp$1.parseStatement (node_modules/rollup-plugin-amd/node_modules/acorn/dist/acorn.js:780:31)
    at Parser.pp$1.parseBlock (node_modules/rollup-plugin-amd/node_modules/acorn/dist/acorn.js:1112:23)
```

on a file is an ES6 module (has top level import / export statements), which has a dynamic `import` inline in one of the functions.

I suspect this would be fixed if I could provide acorn the `ecmaVersion` to use, but afaict this plugin doesn't expose access to the acorn options.

Obviously I don't need to apply the plugin to the file that's causing this, but it would be nice if avoiding that was just a performance optimization, and not actually the difference between a working and a failing build.

**Comment by piuccio** [comment]
if you look at the [code](https://github.com/piuccio/rollup-plugin-amd/blob/master/src/index.js) you'll see that this plugin is a very thin layer on top of [amd-to-es6](https://github.com/buxlabs/amd-to-es6).

I don't think they allow to configure acorn, so maybe you can open an issue / PR over to that repo and I'll bump the version if necessary once the issue gets fixed upstream

**Comment by dgoldstein0** [comment]
thanks for the quick response.  I'll file upstream, but I'm still figuring out how to best set up my rollup build.  At the moment I'm not sure I'll need to use this plugin, so I probably won't start sending any pull requests until I'm sure it's necessary for my use case.

**Comment by dgoldstein0** [comment]
amd-to-es6@0.13.1 is supposed to solve this.  Looks like your package.json doesn't lock down the version of that, so I don't think any action is needed here - I'll give it a shot at some point and see if it works.

**Comment by dgoldstein0** [comment]
I'm going to close this for now, and will reopen if I find it's not fixed.  I haven't had a chance to test it yet for the record, but I expect it to work.
