### ISSUE TITLE
Package is not in the npm registry

### ISSUE THREAD

**Issue by Grawl** [piuccio/rollup-plugin-amd#5]
Cannot install from npm:

```sh
$ npm install --save-dev rollup-pluign-amd
npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/Cellar/node/7.0.0/bin/node" "/usr/local/bin/npm" "install" "--save-dev" "rollup-pluign-amd"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.9
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/rollup-pluign-amd
npm ERR! 404 
npm ERR! 404  'rollup-pluign-amd' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/grawl/Sites/…/npm-debug.log
```

But can install from GitHub:

```sh
$ npm i -D piuccio/rollup-plugin-amd
…@ /Users/grawl/Sites/…
└─┬ rollup-plugin-amd@1.1.1  (git://github.com/piuccio/rollup-plugin-amd.git#366d2778a0213744466ee677ceb7a6528a3238de)
  └─┬ buxlabs.amd-to-es6@0.5.5 
    ├── acorn@4.0.3 
    ├─┬ escodegen@1.8.1 
    │ ├── estraverse@1.9.3 
    │ └── source-map@0.2.0 
    ├── glob@7.0.6 
    ├─┬ js-beautify@1.6.4 
    │ ├─┬ config-chain@1.1.11 
    │ │ └── proto-list@1.2.4 
    │ └─┬ editorconfig@0.13.2 
    │   └── lru-cache@3.2.0 
    └── underscore.string@3.3.4 
```

**Comment by Grawl** [comment]
And it's broken when I trying to load it from `rollup-load-plugins`:

``` js
const $rollup = require('rollup-load-plugins')()
rollup({
    plugins: [
        …
        $rollup.amd,
        …
    ]
})
…
```

``` sh
/usr/local/bin/node /Users/grawl/Sites/…/node_modules/gulp/bin/gulp.js --color --gulpfile /Users/grawl/Sites/…/gulpfile.js :live
/Users/grawl/Sites/…/node_modules/resolve/lib/sync.js:33
    throw new Error("Cannot find module '" + x + "' from '" + y + "'");
    ^

Error: Cannot find module 'rollup-plugin-amd' from '/Users/grawl/Sites/…'
    at Function.module.exports [as sync] (/Users/grawl/Sites/…/node_modules/resolve/lib/sync.js:33:11)
    at /Users/grawl/Sites/…/node_modules/rollup-load-plugins/lib/index.js:88:40
    at Object.memoized [as amd] (/Users/grawl/Sites/…/node_modules/mem/index.js:25:16)
    at Object.<anonymous> (/Users/grawl/Sites/…/gulp-config.js:44:11)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)

Process finished with exit code 1
```

Even directly:

``` js
const rollupAmd = require('rollup-plugin-amd')
rollup({
    plugins: [
        …
        rollupAmd,
        …
    ]
})
…
```

``` sh
/usr/local/bin/node /Users/grawl/Sites/…/node_modules/gulp/bin/gulp.js --color --gulpfile /Users/grawl/Sites/…/gulpfile.js :live
module.js:474
    throw err;
    ^

Error: Cannot find module 'rollup-plugin-amd'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/grawl/Sites/…/gulp-config.js:3:20)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)

Process finished with exit code 1
```

But package folder **is** in `node_modules/rollup-plugin-amd` and has a `package.json` where `"name"` is `"rollup-plugin-amd"`

**Comment by piuccio** [comment]
It has to do with #3 

You copied / paste the wrong line:

```
$ npm install --save-dev rollup-pluign-amd
```

should be 

```
$ npm install --save-dev rollup-plugin-amd
```

`pluign` -> `plugin`

**Comment by Grawl** [comment]
Ahahah I was too bored 😅👍
